// Generated by Selenium IDE
package com_nozama.txt;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;

public class GlobalTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
private String baseURL;
private Object wait;
  
 @Before
 public void testGoogleSearch() throws InterruptedException {
	    // Optional. If not specified, WebDriver searches the PATH for chromedriver.
	    System.setProperty("webdriver.chrome.driver", "C:\\Users\\Administrateur\\Desktop\\chromedriver_win32\\chromedriver.exe");
	    
	    driver = new ChromeDriver();
	    baseURL = "https://www.google.com/";
	    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
 }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void global() {
    driver.get("http://127.0.0.1/nozama/");
    driver.manage().window().setSize(new Dimension(596, 725));
    {
        List<WebElement> elements = driver.findElements(By.id("edit-name"));
        assert(elements.size() > 0);
      }
      {
        List<WebElement> elements = driver.findElements(By.id("edit-pass"));
        assert(elements.size() > 0);
      }
      
    driver.findElement(By.id("edit-name")).click();
    driver.findElement(By.id("edit-name")).sendKeys("demo1");
    driver.findElement(By.id("edit-pass")).click();
    driver.findElement(By.id("edit-pass")).sendKeys("demo1");
    driver.findElement(By.id("edit-submit")).click();
    {
        WebDriverWait wait = new WebDriverWait(driver, 30);
        wait.until(ExpectedConditions.presenceOfElementLocated(By.linkText("Se déconnecter")));
      }
    driver.findElement(By.linkText("Jeux vidéo (5)")).click();
    driver.findElement(By.linkText("Playstation")).click();
    driver.findElement(By.id("edit-submit-16")).click();
    driver.findElement(By.id("edit-search-theme-form-header")).click();
    driver.findElement(By.id("edit-search-theme-form-header")).sendKeys("playstation 5");
    driver.findElement(By.id("edit-submit-2")).click();
    driver.findElement(By.id("edit-search-theme-form-header")).click();
    driver.findElement(By.id("edit-search-theme-form-header")).sendKeys("playstation 3");
    driver.findElement(By.id("edit-submit-2")).click();
    driver.findElement(By.linkText("Sony PlayStation 3")).click();
    driver.findElement(By.id("edit-submit-16")).click();
    driver.findElement(By.linkText("Mon panier")).click();
    driver.findElement(By.id("edit-items-0-remove")).click();
    driver.findElement(By.id("edit-update")).click();
    driver.findElement(By.linkText("Se déconnecter")).click();
    driver.close();
  }
}